# Copyright (C) 2025, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

name: CI Build

env:
  WORK_DIR: /tmp/seapath_cibuild13_${{ github.run_id }}_${{ github.run_attempt }}_${{ github.sha }}

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  workflow_call:
  workflow_dispatch:

permissions:
  actions: write
  checks: write

jobs:
  CI-build:
    runs-on: [self-hosted, runner-RTE-cibuild13]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make build_iso.sh executable (if needed)
        run: chmod +x .release/generate_images.sh

      - name: Run release script
        run: |
          .release/generate_images.sh
        shell: bash

      - name: Check exit code
        run: echo "Script exited successfully!"
